/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.sa.ambulanta.forms;

import rs.ac.bg.fon.sa.ambulanta.domain.*;
import java.awt.Frame;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.NumberEditor;
import javax.swing.SpinnerNumberModel;
import rs.ac.bg.fon.sa.ambulanta.threads.*;
import rs.ac.bg.fon.sa.ambulanta.controller.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;


/**
 *
 * @author Korisnik
 */
public class FrmAnimal extends javax.swing.JDialog {

    int mode;
    Animal animal;
  
    
    public FrmAnimal(Frame parent, boolean modal, int mode, Animal animal) {
        super(parent, modal);
        this.mode = mode;
        if(mode == FormMode.FORM_ADD_MODE){
            this.animal = new Animal();
        }else{
            this.animal = animal;
        }
        initComponents();
       
        populateComboBox();
        setSpinner();
   
        prepareView();
        setLocationRelativeTo(null);
        
        SelectOwnerThread ownerThread = new SelectOwnerThread(this);
        ownerThread.start();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cbSpecies = new javax.swing.JComboBox();
        cbGender = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIDAnimal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNameAnimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAddAnimal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spYearOfBirth = new javax.swing.JSpinner();
        lblName = new javax.swing.JLabel();
        lblYearOfBirth1 = new javax.swing.JLabel();
        lblYearOfBirth = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnFindOwner = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtFirstnameOwner = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLastnameOwner = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        chkLoyaltyCard = new javax.swing.JCheckBox();
        cbOwners = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtJMBGOwner = new javax.swing.JTextField();
        lblJMBG = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnSaveAnimal = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel15.setText("Životinja:");

        jLabel6.setText("godina rođenja:");

        jLabel1.setText("ID:");

        jLabel2.setText("naziv:");

        jLabel3.setText("vrsta:");

        btnAddAnimal.setText("Kreiraj");
        btnAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnimalActionPerformed(evt);
            }
        });

        jLabel5.setText("pol:");

        lblName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 0, 0));

        lblYearOfBirth1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblYearOfBirth1.setForeground(new java.awt.Color(0, 0, 51));
        lblYearOfBirth1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYearOfBirth1.setText("0 - ako je nepoznata");

        lblYearOfBirth.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblYearOfBirth.setForeground(new java.awt.Color(204, 0, 0));
        lblYearOfBirth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAddAnimal)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spYearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblYearOfBirth1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNameAnimal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIDAnimal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addComponent(lblYearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnAddAnimal))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIDAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spYearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYearOfBirth1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("JMBG:");

        btnFindOwner.setText("Pronađi");
        btnFindOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindOwnerActionPerformed(evt);
            }
        });

        jLabel8.setText("ime:");

        jLabel9.setText("prezime:");

        jLabel10.setText("kartica lojalnosti:");

        jLabel11.setText("telefon:");

        jLabel12.setText("email:");

        jLabel13.setText("adresa:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel14.setText("Vlasnik:");

        lblJMBG.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblJMBG.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addContainerGap()
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        							.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(chkLoyaltyCard)
        								.addComponent(lblJMBG, GroupLayout.PREFERRED_SIZE, 290, GroupLayout.PREFERRED_SIZE))
        							.addGap(0, 1, Short.MAX_VALUE))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel2Layout.createSequentialGroup()
        									.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING, false)
        										.addComponent(txtAddress, Alignment.LEADING)
        										.addComponent(txtEmail, Alignment.LEADING)
        										.addComponent(txtPhone, Alignment.LEADING)
        										.addComponent(txtLastnameOwner, Alignment.LEADING)
        										.addComponent(txtFirstnameOwner, Alignment.LEADING)
        										.addComponent(txtJMBGOwner, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(btnFindOwner))
        								.addComponent(cbOwners, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)))))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel14)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGap(8)
        							.addComponent(cbOwners, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addGap(18)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtJMBGOwner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel7)
        						.addComponent(btnFindOwner)))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(3)
        			.addComponent(lblJMBG, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtFirstnameOwner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel8))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtLastnameOwner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel9))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(chkLoyaltyCard)
        				.addComponent(jLabel10))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel11)
        				.addComponent(txtPhone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(6)
        					.addComponent(jLabel12))
        				.addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(6)
        					.addComponent(jLabel13))
        				.addComponent(txtAddress, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        btnSaveAnimal.setText("Sačuvaj");
        btnSaveAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAnimalActionPerformed(evt);
            }
        });

        btnCancel.setText("Izađi");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(14)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(11)
        					.addComponent(btnSaveAnimal, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
        					.addComponent(btnCancel)
        					.addGap(18)))
        			.addGap(18))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(15)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 253, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnSaveAnimal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnCancel))
        			.addGap(14))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindOwnerActionPerformed
                
                validateForm1();
                
                boolean contains = false;
                for (int i = 0; i < cbOwners.getItemCount(); i++) {
                    Owner a = (Owner) cbOwners.getItemAt(i);
                    if (a.getJmbg().toString().equals(txtJMBGOwner.getText())) {
                        cbOwners.setSelectedIndex(i);
                        contains=true;
                        break;
                    }
                }

                if(contains==false){
                    JOptionPane.showMessageDialog(this, "Nije pronađen vlasnik sa zadatim JMBG-om", "Greška", JOptionPane.ERROR_MESSAGE);
                    txtJMBGOwner.setText("");
                }
                
    }//GEN-LAST:event_btnFindOwnerActionPerformed

    private void btnAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnimalActionPerformed
        try {
            if(animal.getId()!=null) throw new Exception("Sistem je vec kreirao životinju.");  

            Owner owner = (Owner) cbOwners.getItemAt(0);
            animal.setName("nema");
            animal.setSpecies(Species.OSTALO);
            animal.setYearOfBirth(0);
            animal.setGender(Gender.MUSKI);
            animal.setOwner(owner);
            
            animal = Controller.getInstance().addNewAnimal(animal);
            
            animal.setId(animal.getId());
            txtIDAnimal.setText(animal.getId().toString());  
            
            JOptionPane.showMessageDialog(this, "Sistem je kreirao životinju ["+animal.getId()+"]", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da kreira životinju.", "Greška", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnAddAnimalActionPerformed

    private void btnSaveAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAnimalActionPerformed
         try {
             
            if(animal.getId()==null) throw new Exception("Prvo morate kreirati životinju!");
            if(cbSpecies.getSelectedItem()==null) throw new Exception("Morate uneti vrstu!");
            if(cbGender.getSelectedItem()==null) throw new Exception("Morate uneti pol!");
                
//            validateForm();
            
            animal.setSpecies((Species) cbSpecies.getSelectedItem());
            animal.setGender((Gender) cbGender.getSelectedItem());
            animal.setId(Long.valueOf(txtIDAnimal.getText()));
            animal.setYearOfBirth((int) spYearOfBirth.getValue());
            if(!txtNameAnimal.getText().isEmpty()) {
                animal.setName(txtNameAnimal.getText());
            } else animal.setName("nema");
            Owner owner = (Owner) cbOwners.getSelectedItem();
            animal.setOwner(owner);
            
            animal = Controller.getInstance().editAnimal(animal);
        
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio životniju ["+animal.getId()+"]", "Informacija", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);

            FrmAnimal form = new FrmAnimal( (Frame)this.getParent(),true,FormMode.FORM_VIEW_MODE, animal);
            form.setVisible(true);
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti životinju.", "Greška", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnSaveAnimalActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        if(mode==FormMode.FORM_ADD_MODE ){
            if(animal.getId()!=null){
                JOptionPane.showMessageDialog(this, "Ne možete da zatvorite prozor dok ne dovršite kreiranje životinje", "Upozorenje", JOptionPane.ERROR_MESSAGE);
            } else dispose();
        }else dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnimal;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFindOwner;
    private javax.swing.JButton btnSaveAnimal;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JComboBox cbOwners;
    private javax.swing.JComboBox cbSpecies;
    private javax.swing.JCheckBox chkLoyaltyCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblJMBG;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblYearOfBirth;
    private javax.swing.JLabel lblYearOfBirth1;
    private javax.swing.JSpinner spYearOfBirth;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstnameOwner;
    private javax.swing.JTextField txtIDAnimal;
    private javax.swing.JTextField txtJMBGOwner;
    private javax.swing.JTextField txtLastnameOwner;
    private javax.swing.JTextField txtNameAnimal;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private void populateComboBox() {
        
        try {
            cbSpecies.setModel(new DefaultComboBoxModel(Species.values()));
            cbSpecies.setSelectedIndex(-1);
            
            cbGender.setModel(new DefaultComboBoxModel(Gender.values()));
            cbGender.setSelectedIndex(-1);
            
            List<Owner> owners = new ArrayList<>();
            owners = Controller.getInstance().getAllOwners();
            cbOwners.setModel(new DefaultComboBoxModel(owners.toArray()));
            cbOwners.setSelectedIndex(-1);
            
        } catch (Exception ex) {
            System.out.println("Nisu ucitani vlasnici. Doslo je do greske.");
        }
        
    }
    
    private void setSpinner() {
        SpinnerNumberModel spinerModel = new SpinnerNumberModel(LocalDate.now().getYear(), 0,LocalDate.now().getYear() , 1);
        spYearOfBirth.setModel(spinerModel);
        NumberEditor editor = new NumberEditor(spYearOfBirth, "0");
        spYearOfBirth.setEditor(editor);
    }

    private void prepareView() {
        
        txtIDAnimal.setEditable(false);
        
        if(mode==FormMode.FORM_ADD_MODE){

            txtFirstnameOwner.setEditable(false);
            txtLastnameOwner.setEditable(false);
            chkLoyaltyCard.setEnabled(false);
            txtPhone.setEditable(false);
            txtEmail.setEditable(false);
            txtAddress.setEditable(false);
        }
        
        if (mode == FormMode.FORM_VIEW_MODE) {

            txtIDAnimal.setText(animal.getId().toString());
            txtNameAnimal.setText(animal.getName());

            for (int i = 0; i < cbSpecies.getItemCount(); i++) {
                Species s = (Species) cbSpecies.getItemAt(i);
                if (s.equals(animal.getSpecies())) {
                    cbSpecies.setSelectedIndex(i);
                    break;
                }
            }

            for (int i = 0; i < cbGender.getItemCount(); i++) {
                Gender g = (Gender) cbGender.getItemAt(i);
                if (g.equals(animal.getGender())) {
                    cbGender.setSelectedIndex(i);
                    break;
                }
            }

            spYearOfBirth.setValue(animal.getYearOfBirth());

            txtJMBGOwner.setText(animal.getOwner().getJmbg().toString());
            txtFirstnameOwner.setText(animal.getOwner().getFirstname());
            txtLastnameOwner.setText(animal.getOwner().getLastname());
            chkLoyaltyCard.setSelected(animal.getOwner().getLoyaltyCard());
            txtPhone.setText(animal.getOwner().getPhone());
            txtEmail.setText(animal.getOwner().getEmail());
            txtAddress.setText(animal.getOwner().getAddress());

                cbOwners.setVisible(false);
                btnFindOwner.setVisible(false);
                btnAddAnimal.setVisible(false);
                btnSaveAnimal.setVisible(false);

                txtNameAnimal.setEditable(false);
                spYearOfBirth.setEnabled(false);
                cbSpecies.setEnabled(false);
                cbGender.setEnabled(false);
                
                

                txtJMBGOwner.setEditable(false);
                txtFirstnameOwner.setEditable(false);
                txtLastnameOwner.setEditable(false);
                chkLoyaltyCard.setEnabled(false);
                txtPhone.setEditable(false);
                txtEmail.setEditable(false);
                txtAddress.setEditable(false);

                setSize(460, 680);
        }
    }

    public void populateOwnerFields() {
        
          Owner owner = (Owner) cbOwners.getSelectedItem();
          if(owner!=null){
          txtFirstnameOwner.setText(owner.getFirstname());
          txtLastnameOwner.setText(owner.getLastname());
          if(owner.getLoyaltyCard()==true){
              chkLoyaltyCard.setSelected(true);
          } else chkLoyaltyCard.setSelected(false);
          txtPhone.setText(owner.getPhone());
          txtEmail.setText(owner.getEmail());
          txtAddress.setText(owner.getAddress());
          }
    }

    private void validateForm1() {
        lblJMBG.setText("");
        
        if(!txtJMBGOwner.getText().matches("\\d{13}")){
            lblJMBG.setText("Unesite 13-ocifren broj");
        }
    }
}
