/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.sa.ambulanta.forms;

import rs.ac.bg.fon.sa.ambulanta.domain.*;
import java.awt.Frame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.sa.ambulanta.model.*;
import rs.ac.bg.fon.sa.ambulanta.controller.*;


/**
 *
 * @author Korisnik
 */
public class FrmFindIntervention extends javax.swing.JDialog{

 
    
    public FrmFindIntervention(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        populateTable();
        
        setLocationRelativeTo(null);
        
        disableTextFields();
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIntervention = new javax.swing.JTable();
        btnShowIntervention = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        chkIDIntervention = new javax.swing.JCheckBox();
        chkIDVeterinarian = new javax.swing.JCheckBox();
        chkIDAnimal = new javax.swing.JCheckBox();
        chkNameService = new javax.swing.JCheckBox();
        chkDateIntervention = new javax.swing.JCheckBox();
        chkAmountGreaterThan = new javax.swing.JCheckBox();
        chkAmountLessThan = new javax.swing.JCheckBox();
        chkLastnameVeterinarian = new javax.swing.JCheckBox();
        chkSpeciesAnimal = new javax.swing.JCheckBox();
        txtIDIntervention = new javax.swing.JTextField();
        txtIDVeterinarian = new javax.swing.JTextField();
        txtIDAnimal = new javax.swing.JTextField();
        txtNameService = new javax.swing.JTextField();
        txtDateIntervention = new javax.swing.JTextField();
        txtAmountGreaterThan = new javax.swing.JTextField();
        txtAmountLessThan = new javax.swing.JTextField();
        txtLastnameVeterinarian = new javax.swing.JTextField();
        txtSpeciesAnimal = new javax.swing.JTextField();
        btnEditIntervention = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chkAll = new javax.swing.JCheckBox();
        chkSort = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lblIDIntervention = new javax.swing.JLabel();
        lblIDVeterinarian = new javax.swing.JLabel();
        lblIDAnimal = new javax.swing.JLabel();
        lblNameService = new javax.swing.JLabel();
        lblDateIntervention = new javax.swing.JLabel();
        lblAmountGraterThan = new javax.swing.JLabel();
        lblAmountLessThan = new javax.swing.JLabel();
        lblLastanameVeterinarian = new javax.swing.JLabel();
        lblSpecies = new javax.swing.JLabel();
        lblDateIntervention1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Kriterijumi pretrage:");

        tblIntervention.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id intervencije", "datum", "veterinar", "životinja"
            }
        ));
        jScrollPane1.setViewportView(tblIntervention);

        btnShowIntervention.setText("Detalji");
        btnShowIntervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowInterventionActionPerformed(evt);
            }
        });

        btnFind.setText("Pretraži");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        chkIDIntervention.setText("ID intervencije:");
        chkIDIntervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIDInterventionActionPerformed(evt);
            }
        });

        chkIDVeterinarian.setText("ID veterinara:");
        chkIDVeterinarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIDVeterinarianActionPerformed(evt);
            }
        });

        chkIDAnimal.setText("ID životinje:");
        chkIDAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIDAnimalActionPerformed(evt);
            }
        });

        chkNameService.setText("naziv usluge:");
        chkNameService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNameServiceActionPerformed(evt);
            }
        });

        chkDateIntervention.setText("datum intervencije:");
        chkDateIntervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDateInterventionActionPerformed(evt);
            }
        });

        chkAmountGreaterThan.setText("iznos veći od:");
        chkAmountGreaterThan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAmountGreaterThanActionPerformed(evt);
            }
        });

        chkAmountLessThan.setText("iznos manji od:");
        chkAmountLessThan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAmountLessThanActionPerformed(evt);
            }
        });

        chkLastnameVeterinarian.setText("prezime veterinara:");
        chkLastnameVeterinarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLastnameVeterinarianActionPerformed(evt);
            }
        });

        chkSpeciesAnimal.setText("vrsta životinje:");
        chkSpeciesAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSpeciesAnimalActionPerformed(evt);
            }
        });

        btnEditIntervention.setText("Izmeni");
        btnEditIntervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInterventionActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));
        jPanel2.setToolTipText("");

        chkAll.setText("Prikaži sve");
        chkAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAllActionPerformed(evt);
            }
        });

        chkSort.setText("Sortiraj po datumu");
        chkSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(chkAll, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(chkSort, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(chkAll)
                .addGap(26, 26, 26)
                .addComponent(chkSort)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Intervencije");

        btnCancel.setText("Izađi");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblIDIntervention.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblIDIntervention.setForeground(new java.awt.Color(204, 0, 0));

        lblIDVeterinarian.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblIDVeterinarian.setForeground(new java.awt.Color(204, 0, 0));

        lblIDAnimal.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblIDAnimal.setForeground(new java.awt.Color(204, 0, 0));

        lblNameService.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblNameService.setForeground(new java.awt.Color(204, 0, 0));

        lblDateIntervention.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblDateIntervention.setForeground(new java.awt.Color(204, 0, 0));

        lblAmountGraterThan.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblAmountGraterThan.setForeground(new java.awt.Color(204, 0, 0));

        lblAmountLessThan.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblAmountLessThan.setForeground(new java.awt.Color(204, 0, 0));

        lblLastanameVeterinarian.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblLastanameVeterinarian.setForeground(new java.awt.Color(204, 0, 0));

        lblSpecies.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        lblSpecies.setForeground(new java.awt.Color(204, 0, 0));

        lblDateIntervention1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblDateIntervention1.setForeground(new java.awt.Color(0, 0, 102));
        lblDateIntervention1.setText("format: dd.mm.ggg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(chkIDVeterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkIDAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkNameService, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkDateIntervention)
                                            .addComponent(chkIDIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkAmountLessThan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkAmountGreaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chkSpeciesAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                            .addComponent(chkLastnameVeterinarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtNameService, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblNameService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtDateIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblDateIntervention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtAmountGreaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblAmountGraterThan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtAmountLessThan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblAmountLessThan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtLastnameVeterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblLastanameVeterinarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtSpeciesAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblSpecies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtIDAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblIDAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(9, 9, 9)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(txtIDVeterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblIDVeterinarian, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(txtIDIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lblIDIntervention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 146, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnShowIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnEditIntervention)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(317, 317, 317)
                    .addComponent(lblDateIntervention1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(346, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIDIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkIDIntervention))
                    .addComponent(lblIDIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIDVeterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkIDVeterinarian))
                    .addComponent(lblIDVeterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIDAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkIDAnimal))
                            .addComponent(lblIDAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNameService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkNameService))
                            .addComponent(lblNameService, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDateIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkDateIntervention))
                            .addComponent(lblDateIntervention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmountGraterThan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAmountGreaterThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkAmountGreaterThan))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAmountLessThan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkAmountLessThan))
                    .addComponent(lblAmountLessThan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLastnameVeterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkLastnameVeterinarian))
                    .addComponent(lblLastanameVeterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSpeciesAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkSpeciesAnimal))
                    .addComponent(lblSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowIntervention)
                    .addComponent(btnEditIntervention)
                    .addComponent(btnCancel))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(218, 218, 218)
                    .addComponent(lblDateIntervention1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(537, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
           
        try {
            validateForm();
            
            chkAll.setSelected(false);
            chkSort.setSelected(false);
            
            List<Intervention> interventions = new ArrayList<>();
            
            if(chkIDIntervention.isSelected()){
                List<Intervention> interventions1 = new ArrayList<>();
                String criteria = txtIDIntervention.getText();
                interventions1 = Controller.getInstance().getInterventionsByInterventionCriteria(criteria);
                interventions.addAll(interventions1);
            }
            if(chkIDVeterinarian.isSelected()){
                List<Intervention> interventions1 = new ArrayList<>();
                String criteria = txtIDVeterinarian.getText();
                interventions1 = Controller.getInstance().getInterventionsByVeterinarianCriteria(criteria);
                if(interventions.isEmpty()){
                   interventions.addAll(interventions1); 
                } else interventions.retainAll(interventions1); //DODAJE U LISTU samo zajednicke elemente (AND-presek logika)
                                                                    //U klasi Intervention mora da se uradi override equals() i hashCode() metoda po id-ju
                                                                    //kako bi se elementi poredili po id-u a ne referenci 
            }
            
            if(chkIDAnimal.isSelected()){
                List<Intervention> interventions1 = new ArrayList<>();
                String criteria = txtIDAnimal.getText();
                interventions1 = Controller.getInstance().getInterventionsByAnimalCriteria(criteria);
                if(interventions.isEmpty()){
                   interventions.addAll(interventions1); 
                } else interventions.retainAll(interventions1);
            }
            
            
            if(chkNameService.isSelected()){ 
                List<Intervention> interventions1 = new ArrayList<>();
                String criteria = txtNameService.getText();
                interventions1 = Controller.getInstance().getInterventionsByServiceCriteria(criteria);
                if(interventions.isEmpty()){
                   interventions.addAll(interventions1); 
                } else interventions.retainAll(interventions1);
            }
            
            if(chkDateIntervention.isSelected()){
                List<Intervention> interventions1 = new ArrayList<>();
                String criteria = txtDateIntervention.getText();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
                LocalDate localDate = LocalDate.parse(criteria, formatter);
                String criteriaDate = localDate.toString();
                criteriaDate=criteriaDate+"Date";//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                interventions1 = Controller.getInstance().getInterventionsByInterventionCriteria(criteriaDate);
                if(interventions.isEmpty()){
                   interventions.addAll(interventions1); 
                } else interventions.retainAll(interventions1);
            }
            
            if(chkAmountGreaterThan .isSelected()){
                List<Intervention> interventions1 = new ArrayList<>();
                String criteria = txtAmountGreaterThan.getText();
                criteria=criteria+">";//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                interventions1 = Controller.getInstance().getInterventionsByInterventionCriteria(criteria);
                if(interventions.isEmpty()){
                   interventions.addAll(interventions1); 
                } else interventions.retainAll(interventions1);
            }
            
            if(chkAmountLessThan .isSelected()){
                List<Intervention> interventions1 = new ArrayList<>();
                String criteria = txtAmountLessThan.getText();
                criteria=criteria+"<";//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                interventions1 = Controller.getInstance().getInterventionsByInterventionCriteria(criteria);
                if(interventions.isEmpty()){
                   interventions.addAll(interventions1); 
                } else interventions.retainAll(interventions1);
            }
            
            if(chkLastnameVeterinarian.isSelected()){
                List<Intervention> interventions1 = new ArrayList<>();
                String criteria = txtLastnameVeterinarian.getText();
                criteria=criteria+"Lastname";//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                interventions1 = Controller.getInstance().getInterventionsByVeterinarianCriteria(criteria);
                if(interventions.isEmpty()){
                   interventions.addAll(interventions1); 
                } else interventions.retainAll(interventions1);
            }
            
            
            if(chkSpeciesAnimal.isSelected()){
                List<Intervention> interventions1 = new ArrayList<>();
                String criteria = txtSpeciesAnimal.getText();
                criteria=criteria+"Species";//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                interventions1 = Controller.getInstance().getInterventionsByAnimalCriteria(criteria);
                if(interventions.isEmpty()){
                   interventions.addAll(interventions1); 
                } else interventions.retainAll(interventions1);
            }

            
            interventions = interventions.stream().distinct().collect(Collectors.toList());
            tblIntervention.setModel(new TableModelIntervention(interventions));

            
            if(!interventions.isEmpty()){
                JOptionPane.showMessageDialog(this, "Sistem je našao interevncije po zadatim kriterijumima", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe intervencije po zadatim kriterijumima!", "Greska", JOptionPane.ERROR_MESSAGE);
            }
            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe intervencije po zadatim kriterijumima!\n"+ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe intervencije po zadatim kriterijumima.", "Greska", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
            
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnShowInterventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowInterventionActionPerformed
        try {
            int row = tblIntervention.getSelectedRow();
            TableModelIntervention itm = (TableModelIntervention) tblIntervention.getModel();
            Intervention intervention = itm.getIntervention(row);
            
            intervention = Controller.getInstance().getIntervention(intervention);
            
            JOptionPane.showMessageDialog(this, "Sistem je našao intervenciju", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            FrmViewEditIntervention form = new FrmViewEditIntervention((Frame)this.getParent(), true, FormMode.FORM_VIEW_MODE, intervention);
            form.setVisible(true);
            
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Sistem ne može da nađe intervenciju", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnShowInterventionActionPerformed

    private void chkIDInterventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIDInterventionActionPerformed
        if (chkIDIntervention.isSelected()) {
            txtIDIntervention.setEditable(true);
        } else {
            txtIDIntervention.setText("");
            txtIDIntervention.setEditable(false);
        }
    }//GEN-LAST:event_chkIDInterventionActionPerformed

    private void chkIDVeterinarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIDVeterinarianActionPerformed
        if (chkIDVeterinarian.isSelected()) {
            txtIDVeterinarian.setEditable(true);
        } else {
            txtIDVeterinarian.setText("");
            txtIDVeterinarian.setEditable(false);
        }
    }//GEN-LAST:event_chkIDVeterinarianActionPerformed

    private void chkIDAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIDAnimalActionPerformed
        if (chkIDAnimal.isSelected()) {
            txtIDAnimal.setEditable(true);
        } else {
            txtIDAnimal.setText("");
            txtIDAnimal.setEditable(false);
        }
    }//GEN-LAST:event_chkIDAnimalActionPerformed

    private void chkNameServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNameServiceActionPerformed
        if (chkNameService.isSelected()) {
            txtNameService.setEditable(true);
        } else {
            txtNameService.setText("");
            txtNameService.setEditable(false);
        }
    }//GEN-LAST:event_chkNameServiceActionPerformed

    private void chkDateInterventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDateInterventionActionPerformed
        if (chkDateIntervention.isSelected()) {
            txtDateIntervention.setEditable(true);
        } else {
            txtDateIntervention.setText("");
            txtDateIntervention.setEditable(false);
        }

    }//GEN-LAST:event_chkDateInterventionActionPerformed

    private void chkAmountGreaterThanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAmountGreaterThanActionPerformed
        if (chkAmountGreaterThan.isSelected()) {
            txtAmountGreaterThan.setEditable(true);
        } else {
            txtAmountGreaterThan.setText("");
            txtAmountGreaterThan.setEditable(false);
        }
    }//GEN-LAST:event_chkAmountGreaterThanActionPerformed

    private void chkAmountLessThanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAmountLessThanActionPerformed
        if (chkAmountLessThan.isSelected()) {
            txtAmountLessThan.setEditable(true);
        } else {
            txtAmountLessThan.setText("");
            txtAmountLessThan.setEditable(false);
        }

    }//GEN-LAST:event_chkAmountLessThanActionPerformed

    private void chkLastnameVeterinarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLastnameVeterinarianActionPerformed
        if (chkLastnameVeterinarian.isSelected()) {
            txtLastnameVeterinarian.setEditable(true);
        } else {
            txtLastnameVeterinarian.setText("");
            txtLastnameVeterinarian.setEditable(false);
        }
    }//GEN-LAST:event_chkLastnameVeterinarianActionPerformed

    private void chkSpeciesAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSpeciesAnimalActionPerformed
        if (chkSpeciesAnimal.isSelected()) {
    txtSpeciesAnimal.setEditable(true);
        } else {
            txtSpeciesAnimal.setText("");
            txtSpeciesAnimal.setEditable(false);
        }
    }//GEN-LAST:event_chkSpeciesAnimalActionPerformed

    private void chkAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAllActionPerformed
        if(chkAll.isSelected()){
            populateTable();
        }
        chkSort.setSelected(false);
        chkIDIntervention.setSelected(false);
        chkIDVeterinarian.setSelected(false);
        chkIDAnimal.setSelected(false);
        chkNameService.setSelected(false);
        chkDateIntervention.setSelected(false);
        chkAmountGreaterThan.setSelected(false);
        chkAmountLessThan.setSelected(false);
        chkLastnameVeterinarian.setSelected(false);
        chkSpeciesAnimal.setSelected(false);
        
        txtIDIntervention.setEditable(false);
        txtIDVeterinarian.setEditable(false);
        txtIDAnimal.setEditable(false);
        txtNameService.setEditable(false);
        txtDateIntervention.setEditable(false);
        txtAmountGreaterThan.setEditable(false);
        txtAmountLessThan.setEditable(false);
        txtLastnameVeterinarian.setEditable(false);
        txtSpeciesAnimal.setEditable(false);
        
        txtIDIntervention.setText("");
        txtIDVeterinarian.setText("");
        txtIDAnimal.setText("");
        txtNameService.setText("");
        txtDateIntervention.setText("");
        txtAmountGreaterThan.setText("");
        txtAmountLessThan.setText("");
        txtLastnameVeterinarian.setText("");
        txtSpeciesAnimal.setText("");
    }//GEN-LAST:event_chkAllActionPerformed

    private void btnEditInterventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInterventionActionPerformed
       try {
            int row = tblIntervention.getSelectedRow();
            TableModelIntervention itm = (TableModelIntervention) tblIntervention.getModel();
            Intervention intervention = itm.getIntervention(row);
            
            intervention = Controller.getInstance().getIntervention(intervention);
            
            JOptionPane.showMessageDialog(this, "Sistem je našao intervenciju", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            FrmViewEditIntervention form = new FrmViewEditIntervention((Frame)this.getParent(), true, FormMode.FORM_EDIT_MODE, intervention);
            form.setVisible(true);
        
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Sistem ne može da nađe intervenciju", "Greška", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditInterventionActionPerformed

    private void chkSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSortActionPerformed
        TableModelIntervention itm = (TableModelIntervention) tblIntervention.getModel();
        itm.sortInterventionsByDate();
        chkAll.setSelected(false);
    }//GEN-LAST:event_chkSortActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEditIntervention;
    private javax.swing.JButton btnFind;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnShowIntervention;
    private javax.swing.JCheckBox chkAll;
    private javax.swing.JCheckBox chkAmountGreaterThan;
    private javax.swing.JCheckBox chkAmountLessThan;
    private javax.swing.JCheckBox chkDateIntervention;
    private javax.swing.JCheckBox chkIDAnimal;
    private javax.swing.JCheckBox chkIDIntervention;
    private javax.swing.JCheckBox chkIDVeterinarian;
    private javax.swing.JCheckBox chkLastnameVeterinarian;
    private javax.swing.JCheckBox chkNameService;
    private javax.swing.JCheckBox chkSort;
    private javax.swing.JCheckBox chkSpeciesAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmountGraterThan;
    private javax.swing.JLabel lblAmountLessThan;
    private javax.swing.JLabel lblDateIntervention;
    private javax.swing.JLabel lblDateIntervention1;
    private javax.swing.JLabel lblIDAnimal;
    private javax.swing.JLabel lblIDIntervention;
    private javax.swing.JLabel lblIDVeterinarian;
    private javax.swing.JLabel lblLastanameVeterinarian;
    private javax.swing.JLabel lblNameService;
    private javax.swing.JLabel lblSpecies;
    private javax.swing.JTable tblIntervention;
    private javax.swing.JTextField txtAmountGreaterThan;
    private javax.swing.JTextField txtAmountLessThan;
    private javax.swing.JTextField txtDateIntervention;
    private javax.swing.JTextField txtIDAnimal;
    private javax.swing.JTextField txtIDIntervention;
    private javax.swing.JTextField txtIDVeterinarian;
    private javax.swing.JTextField txtLastnameVeterinarian;
    private javax.swing.JTextField txtNameService;
    private javax.swing.JTextField txtSpeciesAnimal;
    // End of variables declaration//GEN-END:variables


    private void populateTable() {
        try {
            List<Intervention> interventions = new ArrayList<>();
            
            interventions = Controller.getInstance().getAllInterventions();
            
            tblIntervention.setModel(new TableModelIntervention(interventions));
            
        } catch (Exception ex) {
            System.out.println("Neuspesno ucitane intervencije!");
        }
    }

    private void disableTextFields() {
            txtIDIntervention.setEditable(false);
            txtIDVeterinarian.setEditable(false);
            txtIDAnimal.setEditable(false);
            txtNameService.setEditable(false);
            txtDateIntervention.setEditable(false);
            txtAmountGreaterThan.setEditable(false);
            txtAmountLessThan.setEditable(false);
            txtLastnameVeterinarian.setEditable(false);
            txtSpeciesAnimal.setEditable(false);
    }

    private void validateForm() throws Exception {
        Boolean error=false;
        lblAmountGraterThan.setText("");
        lblAmountLessThan.setText("");
        lblIDAnimal.setText("");
        lblIDIntervention.setText("");
        lblNameService.setText("");
        lblIDVeterinarian.setText("");
        lblDateIntervention.setText("");
        lblDateIntervention1.setVisible(true);
        lblLastanameVeterinarian.setText("");
        lblSpecies.setText("");
        
        if (!txtAmountGreaterThan.getText().matches("\\d+") && chkAmountGreaterThan.isSelected()) {
            lblAmountGraterThan.setText("Polje sme da sadrži samo brojeve");
            error=true;
            
        }
        if (!txtAmountLessThan.getText().matches("\\d+") && chkAmountLessThan.isSelected()) {
            lblAmountLessThan.setText("Polje sme da sadrži samo brojeve");
            error=true;
        }
        if (!txtIDAnimal.getText().matches("\\d+") && chkIDAnimal.isSelected()) {
            lblIDAnimal.setText("Polje sme da sadrži samo brojeve");
            error=true;
        }
        if (!txtIDIntervention.getText().matches("\\d+") && chkIDIntervention.isSelected()) {
            lblIDIntervention.setText("Polje sme da sadrži samo brojeve");
            error=true;
        }
        if (!txtIDVeterinarian.getText().matches("\\d+") && chkIDVeterinarian.isSelected()) {
            lblIDVeterinarian.setText("Polje sme da sadrži samo brojeve");
            error=true;
        }
        if (!txtLastnameVeterinarian.getText().matches("[\\p{L} ]+") && chkLastnameVeterinarian.isSelected()) {
            lblLastanameVeterinarian.setText("Polje sme da sadrži samo slova");
            error=true;
        }
        if (!txtNameService.getText().matches("[\\p{L} ]+") && chkNameService.isSelected()) {
            lblNameService.setText("Polje sme da sadrži samo slova");
            error=true;
        }
        if (!txtSpeciesAnimal.getText().matches("[\\p{L} ]+") && chkSpeciesAnimal.isSelected()) {
            lblSpecies.setText("Polje sme da sadrži samo slova");
            error=true;
        }
        
        if (!txtDateIntervention.getText().matches("\\d{2}\\.\\d{2}\\.\\d{4}") && chkDateIntervention.isSelected()) {
            lblDateIntervention1.setVisible(false);
            lblDateIntervention.setText("Datum mora biti u formatu dd.mm.gggg");
            error=true;
  
        }
        
        if(error){
            throw new Exception("Niste ispravno popunili polje/a!");
        }
    }
}
