/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.sa.ambulanta.forms;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import rs.ac.bg.fon.sa.ambulanta.controller.*;
import rs.ac.bg.fon.sa.ambulanta.domain.*;
import rs.ac.bg.fon.sa.ambulanta.threads.*;
import java.awt.Dimension;
import javax.swing.SwingConstants;
import javax.swing.JMenu;
import java.awt.Font;
import javax.swing.JMenuItem;


/**
 *
 * @author Korisnik
 */
public class FrmMain1 extends javax.swing.JFrame {
    
    private final Veterinarian veterinarian;


    
    public FrmMain1() throws Exception{
        try {

        initComponents();
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/image/background1.png")));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png")).getImage());
        
        veterinarian = Controller.getInstance().getCurrentUser();
        setTitle("PetVet :: " + veterinarian.getFirstname() + " " + veterinarian.getLastname());
        lblVeterinarian.setText("dr. vet. med. "+veterinarian.getFirstname()+" "+veterinarian.getLastname());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        DateTimeThread threadDT = new DateTimeThread(lblDate, lblTime);
        threadDT.start();
        
        } catch (Exception ex) {
            throw new Exception("Ne može da se otvori glavna forma i meni.");
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setIcon(null);
        jPanel1 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblVeterinarian = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuIntervention = new javax.swing.JMenu();
        menuIntervention.setHorizontalAlignment(SwingConstants.CENTER);
        menuItemNewIntervention = new javax.swing.JMenuItem();
        menuItemEditIntervention = new javax.swing.JMenuItem();
        menuSpecialization = new javax.swing.JMenu();
        menuItemNewSpecialization = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        lblVeterinarian.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        lblVeterinarian.setForeground(new java.awt.Color(102, 102, 102));
        lblVeterinarian.setText("dr. vet. med. Petar Petrović");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(430, 40));

        menuIntervention.setText("Intervencija");
        menuIntervention.setFont(new java.awt.Font("Segoe UI", 1, 14));
        menuIntervention.setHorizontalTextPosition(SwingConstants.CENTER);
        menuIntervention.setPreferredSize(new Dimension(110, 30));

        menuItemNewIntervention.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemNewIntervention.setText("Kreiraj");
        menuItemNewIntervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewInterventionActionPerformed(evt);
            }
        });
        menuIntervention.add(menuItemNewIntervention);

        menuItemEditIntervention.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemEditIntervention.setText("Pretraži");
        menuItemEditIntervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditInterventionActionPerformed(evt);
            }
        });
        menuIntervention.add(menuItemEditIntervention);

        jMenuBar1.add(menuIntervention);

        menuSpecialization.setText("Specijalizacija");
        menuSpecialization.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuSpecialization.setHorizontalAlignment(SwingConstants.CENTER);
        menuSpecialization.setHorizontalTextPosition(SwingConstants.CENTER);
        menuSpecialization.setPreferredSize(new Dimension(120, 30));

        menuItemNewSpecialization.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemNewSpecialization.setText("Unesi");
        menuItemNewSpecialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewSpecializationActionPerformed(evt);
            }
        });
        
        mnivotinja = new JMenu();
        mnivotinja.setText("Životinja");
        mnivotinja.setPreferredSize(new Dimension(90, 30));
        mnivotinja.setHorizontalTextPosition(SwingConstants.CENTER);
        mnivotinja.setHorizontalAlignment(SwingConstants.CENTER);
        mnivotinja.setFont(new Font("Segoe UI", Font.BOLD, 14));
        jMenuBar1.add(mnivotinja);
        
        mntmKreiraj = new JMenuItem();
        mntmKreiraj.setText("Kreiraj");
        mntmKreiraj.setFont(new Font("Segoe UI", Font.BOLD, 12));
        mnivotinja.add(mntmKreiraj);
        menuSpecialization.add(menuItemNewSpecialization);

        jMenuBar1.add(menuSpecialization);
        
        mntmDodeli = new JMenuItem();
        mntmDodeli.setText("Dodeli");
        mntmDodeli.setFont(new Font("Segoe UI", Font.BOLD, 12));
        menuSpecialization.add(mntmDodeli);
        
        menuItemNewSpecialization_2 = new JMenuItem();
        menuItemNewSpecialization_2.setText("Prikaži");
        menuItemNewSpecialization_2.setFont(new Font("Segoe UI", Font.BOLD, 12));
        menuSpecialization.add(menuItemNewSpecialization_2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblVeterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(560, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblVeterinarian, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemNewInterventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewInterventionActionPerformed
    	try {
            
            FrmNewIntervention form = new FrmNewIntervention(this,true);
            form.setVisible(true);
            form.setLocationRelativeTo(null);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_menuItemNewInterventionActionPerformed

    private void menuItemEditInterventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditInterventionActionPerformed
       
    }//GEN-LAST:event_menuItemEditInterventionActionPerformed

    
    private void menuItemNewSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewSpecializationActionPerformed
        
    }//GEN-LAST:event_menuItemNewSpecializationActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblVeterinarian;
    private javax.swing.JMenu menuIntervention;
    private javax.swing.JMenuItem menuItemEditIntervention;
    private javax.swing.JMenuItem menuItemNewIntervention;
    private javax.swing.JMenuItem menuItemNewSpecialization;
    private javax.swing.JMenu menuSpecialization;
    private JMenu mnivotinja;
    private JMenuItem mntmKreiraj;
    private JMenuItem mntmDodeli;
    private JMenuItem menuItemNewSpecialization_2;
    // End of variables declaration//GEN-END:variables

    
}
